[package]
name = "vkdg-storage"
version.workspace = true
edition.workspace = true
license.workspace = true

[dependencies]
vkdg-core    = { workspace = true }
serde        = { workspace = true }
anyhow       = { workspace = true }
tokio        = { workspace = true }
async-trait  = { workspace = true }
uuid         = { workspace = true }
chrono       = { workspace = true }

[lib]
doctest = false

[lints]
workspace = true
