[package]
name = "vkdg-provider-anthropic"
version.workspace = true
edition.workspace = true
license.workspace = true

[dependencies]
vkdg-core        = { workspace = true }
vkdg-operations  = { workspace = true }
vkdg-connections = { workspace = true }
vkdg-http        = { workspace = true }
bytes            = { workspace = true }
http             = { workspace = true }
serde_json       = { workspace = true }

[lib]
doctest = false
