[package]
name = "vkdg-memory"
version.workspace = true
edition.workspace = true
license.workspace = true

[dependencies]
vkdg-operations  = { workspace = true }
serde            = { workspace = true }
tokio            = { workspace = true }
chrono           = { workspace = true }
uuid             = { workspace = true }

[lib]
doctest = false

[lints]
workspace = true
