[package]
name = "vkdg-memory"
version.workspace = true
edition.workspace = true
license.workspace = true

[dependencies]
vkdg-core        = { workspace = true }
vkdg-operations  = { workspace = true }
serde            = { workspace = true }
serde_json       = { workspace = true }
bytes            = { workspace = true }
tokio            = { workspace = true }
chrono           = { workspace = true }
uuid             = { workspace = true }
thiserror        = { workspace = true }

[lib]
doctest = false
