[package]
name = "vkdg-admin"
version.workspace = true
edition.workspace = true
license.workspace = true

[dependencies]
vkdg-core        = { workspace = true }
vkdg-connections = { workspace = true }
vkdg-plugin-host = { workspace = true }
vkdg-config      = { workspace = true }
vkdg-routing     = { workspace = true }
axum             = { workspace = true }
tokio            = { workspace = true }
serde            = { workspace = true }
serde_json       = { workspace = true }
http             = { workspace = true }
uuid             = { workspace = true }
chrono           = { workspace = true }
vkdg-combos     = { workspace = true }
parking_lot      = { workspace = true }
serde_yaml       = { workspace = true }
vkdg-provider-sdk = { workspace = true }
vkdg-governance  = { workspace = true }
rusqlite         = { workspace = true }
argon2           = { workspace = true }
futures          = { workspace = true }
reqwest          = { workspace = true }

[dev-dependencies]
tower            = { workspace = true }
tempfile         = { workspace = true }
vkdg-operations  = { workspace = true }

[lib]
doctest = false

[lints]
workspace = true
